name: Deploy @vesper/www to vercel

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm and Vercel CLI
        run: npm install -g pnpm vercel

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
